# Generated by Django 2.2.1 on 2019-05-23 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('ONTARIO', 'Ontario'), ('QUEBEC', 'Quebec'), ('NOVA SCOTIA', 'Nova Scotia'), ('NEW BRUNSWICK', 'New Brunswick'), ('MANITOBA', 'Manitoba'), ('BRITISH COLUMBIA', 'British Columbia'), ('PRINCE EDWARD ISLAND', 'Prince Edward Island'), ('SASKATCHEWAN', 'Saskatchewan'), ('ALBERTA', 'Alberta'), ('NEWFOUNDLAND', 'Newfoundland'), ('NORTHWEST TERRITORIES', 'Northwest Territories'), ('YUKON', 'Yukon'), ('NUNAVUT', 'Nunavut')], max_length=100)),
                ('postal_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('phone_type', models.CharField(choices=[('HOME', 'Home'), ('MOBILE', 'Mobile'), ('WORK', 'Work'), ('OTHER', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unidentified/Other')], max_length=1)),
                ('hair_color', models.CharField(choices=[('BLONDE', 'Blonde'), ('BRUNETTE', 'Bruneete'), ('BROWN', 'Brown'), ('BLACK', 'Black'), ('GRAY', 'Gray'), ('RED', 'Red'), ('PURPLE', 'Purple'), ('BLUE', 'Blue'), ('GREEN', 'Green')], max_length=20)),
                ('eye_color', models.CharField(choices=[('GREEN', 'Green'), ('BLUE', 'Blue'), ('HAZEL', 'Hazel'), ('BROWN', 'Brown')], max_length=20)),
                ('social_insurance_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicModeling.Address')),
                ('phone_numbers', models.ManyToManyField(to='BasicModeling.PhoneNumber')),
            ],
        ),
    ]
